### ISSUE TITLE
Mac App not working

### ISSUE THREAD

**Issue by pereleal1** [AngeloTorelli/AutoSeg#1]
I just downloaded AutoCellSeg and tried to run it on my Mac (MacOS High Sierra), but it is not working. First I downloaded the entire AutoCellSeg master repository. Then I installed MATLAB Runtime 9.1 and tried to open the AutoCellSeg Mac application both from Finder and from Terminal (by running run_AutoCellSeg.sh). However, all I get when the application opens is a blank window titled "Download" with a completed download progress bar at the bottom. How can I get the app to run properly?

**Comment by AngeloTorelli** [comment]
I am sorry for answering so late but unfortunately we do not have a Mac anymore I had to ask around to borrow it. I finally got one and I can not replicate your error. The only thing I noticed is that you mention "run_AutoCellSeg.sh" which is for Linux based operating systems. For Mac OSX systems you should run the *.app files and since you already installed the MATLAB Runtime 9.1 then you should only execute AutoCellSeg.app which is under (https://github.com/AngeloTorelli/AutoCellSeg/tree/master/Mac/AutoCellSeg.app) I hope this helps you
